services:
  orca:
    container_name: ${CONTAINER_NAME:-orca-auv-rpi-ros2-container}
    image: ${IMAGE_OWNER_NAME:-dianyueguo}/${IMAGE_NAME:-orca-auv-rpi-ros2-image}:latest
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    environment:
      DISPLAY: ${HOST_DISPLAY:-host.docker.internal:0}
      XAUTHORITY: ${XAUTHORITY:-/tmp/.Xauthority}
    volumes:
      - /dev:/dev
      - ./orca_auv_rpi_ros2_ws:/root/orca_auv_rpi_ros2_ws
      - ./SAUVC-STM32/build:/root/orca_auv_rpi_ros2_ws/stm32_binary
      - ${XAUTH_FILE:-/tmp/.Xauthority}:${XAUTHORITY:-/tmp/.Xauthority}:ro
    working_dir: /root
    command: [ "/bin/bash", "-lc", "source /opt/ros/humble/setup.bash && source /root/uros_ws/install/local_setup.bash && cd /root/orca_auv_rpi_ros2_ws && if [ -f install/setup.bash ]; then source install/setup.bash; fi && echo 'Starting API Server...' && (cd src/ocean-navigator-os/server && npm install && npm run dev &) && echo 'Starting ROS System...' && (ros2 launch src/launch/test_launch.py &) && echo 'Starting Frontend...' && cd src/ocean-navigator-os && ( [ ! -d node_modules/@rollup/rollup-linux-arm64-gnu ] && npm install || echo 'Native modules okay' ) && npm run dev -- --host" ]
