ros2 action send_goal /orca_auv/thruster_0/initialize_thruster orca_auv_thruster_interfaces_pkg/action/InitializeThrusterAction "{}"
ros2 action send_goal /orca_auv/thruster_1/initialize_thruster orca_auv_thruster_interfaces_pkg/action/InitializeThrusterAction "{}"
ros2 action send_goal /orca_auv/thruster_2/initialize_thruster orca_auv_thruster_interfaces_pkg/action/InitializeThrusterAction "{}"
ros2 action send_goal /orca_auv/thruster_3/initialize_thruster orca_auv_thruster_interfaces_pkg/action/InitializeThrusterAction "{}"
ros2 action send_goal /orca_auv/thruster_4/initialize_thruster orca_auv_thruster_interfaces_pkg/action/InitializeThrusterAction "{}"
ros2 action send_goal /orca_auv/thruster_5/initialize_thruster orca_auv_thruster_interfaces_pkg/action/InitializeThrusterAction "{}"
ros2 action send_goal /orca_auv/thruster_6/initialize_thruster orca_auv_thruster_interfaces_pkg/action/InitializeThrusterAction "{}"
ros2 action send_goal /orca_auv/thruster_7/initialize_thruster orca_auv_thruster_interfaces_pkg/action/InitializeThrusterAction "{}"
