from enum import Enum


class ControlMode(Enum):
    SAFE_DISABLED = "SAFE_DISABLED"
    MANUAL = "MANUAL"
    DEPTH_HOLD = "DEPTH_HOLD"
    BOTTOM_CAMERA_HOLD = "BOTTOM_CAMERA_HOLD"
    DEPTH_AND_BOTTOM_CAMERA_HOLD = "DEPTH_AND_BOTTOM_CAMERA_HOLD"
    FAULT = "FAULT"
