ros2 service call /orca_auv/thruster_0/initialize_thruster std_srvs/srv/Trigger "{}"
ros2 service call /orca_auv/thruster_1/initialize_thruster std_srvs/srv/Trigger "{}"
ros2 service call /orca_auv/thruster_2/initialize_thruster std_srvs/srv/Trigger "{}"
ros2 service call /orca_auv/thruster_3/initialize_thruster std_srvs/srv/Trigger "{}"
ros2 service call /orca_auv/thruster_4/initialize_thruster std_srvs/srv/Trigger "{}"
ros2 service call /orca_auv/thruster_5/initialize_thruster std_srvs/srv/Trigger "{}"
ros2 service call /orca_auv/thruster_6/initialize_thruster std_srvs/srv/Trigger "{}"
ros2 service call /orca_auv/thruster_7/initialize_thruster std_srvs/srv/Trigger "{}"
